# Esto hace una instalación limpiade node y sus dependencias,
# lo cachea/restaura, construye el codigo y hace pruebas en multiples versiones
#de node.
# Para mas información consultar: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Instalacion limpia de Node.js

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
    #usamos la matriz de versiones para hacer el checkout en multiples versiones.
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm test
